.PHONY: clean All

All:
	@echo "----------Building project:[ CPPWorkspace - Debug ]----------"
	@cd "CPPWorkspace" && "$(MAKE)" -f  "CPPWorkspace.mk"
clean:
	@echo "----------Cleaning project:[ CPPWorkspace - Debug ]----------"
	@cd "CPPWorkspace" && "$(MAKE)" -f  "CPPWorkspace.mk" clean
