.PHONY: clean All

All:
	@echo "----------Building project:[ ChallangeTwo - Debug ]----------"
	@cd "ChallangeTwo" && "$(MAKE)" -f  "ChallangeTwo.mk"
clean:
	@echo "----------Cleaning project:[ ChallangeTwo - Debug ]----------"
	@cd "ChallangeTwo" && "$(MAKE)" -f  "ChallangeTwo.mk" clean
